name: Build and deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup repo
      uses: actions/checkout@v2    
    
    - name: Install pandoc 2.9
      run: |
        wget https://github.com/jgm/pandoc/releases/download/2.11.2/pandoc-2.11.2-1-amd64.deb
        sudo dpkg -i pandoc-2.11.2-1-amd64.deb

    - name: Build slides
      run: |
        make html
    - name: Deploy slides
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ '{{' }} secrets.GITHUB_TOKEN {{ '}}' }}
        publish_dir: build

